http:
  routers:
    homer:
      rule: "Host(`home.dankers.io`)"
      service: homer
      entryPoints:
        - web

    receipts:
      rule: "Host(`receipts.dankers.io`)"
      service: receipts
      entryPoints:
        - web
      middlewares:
        - receipts-headers
