http:
  routers:
    homer:
      rule: "Host(`home.dankers.io`)"
      service: homer
      entryPoints:
        - web

    receipts:
      rule: "Host(`receipts.dankers.io`)"
      service: receipts
      entryPoints:
        - web
      middlewares:
        - receipts-headers

    dozzle:
      rule: "Host(`status.dankers.io`)"
      service: dozzle
      entryPoints:
        - web
      middlewares:
        - dozzle-headers

    adguard:
      rule: "Host(`adguard.dankers.io`)"
      service: adguard
      entryPoints:
        - web
      middlewares:
        - adguard-headers

    audiobookshelf:
      rule: "Host(`audiobooks.dankers.io`)"
      service: audiobookshelf
      entryPoints:
        - web
      middlewares:
        - audiobookshelf-headers
