http:
  services:
    homer:
      loadBalancer:
        servers:
          - url: "http://homer:8080"

    receipts:
      loadBalancer:
        servers:
          - url: "http://receipts:8080"
        passHostHeader: true

    dozzle:
      loadBalancer:
        servers:
          - url: "http://dozzle:8080"

    adguard:
      loadBalancer:
        servers:
          - url: "http://adguardhome:3000"

    audiobookshelf:
      loadBalancer:
        servers:
          - url: "http://audiobookshelf:80"
        passHostHeader: true
